name: Node.js CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: 'dev'

jobs:
  deploy-dev:
    name: Deploy to Dev Environment
    if: github.ref == 'refs/heads/main' && inputs.environment == 'dev'
    runs-on: ${{ github.event.inputs.environment }}-runner
    env:
      RUNNER_LABEL: ip-172-31-7-45  # Define the runner label for dev environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build --if-present

      - name: Restart PM2 (backend-test)
        run: pm2 restart backend-test

  deploy-prod:
    name: Deploy to Prod Environment
    if: github.ref == 'refs/heads/main' && inputs.environment == 'prod'
    runs-on: ${{ github.event.inputs.environment }}-runner
    env:
      RUNNER_LABEL: ip-172-31-2-210  # Define the runner label for prod environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build --if-present

      # - name: Restart PM2 (backend-test)
      # run: pm2 restart backend-test