name: Node.js CI

on:
  push:
    branches: [ "main" ]

  # Manual workflow trigger
  workflow_dispatch:

jobs:
  deploy-dev: # Deploy to the development environment
    if: github.ref == 'refs/heads/main'
    runs-on: ip-172-31-7-45 # Replace with the label for your dev runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build App
      run: npm run build --if-present

    - name: Restart PM2 (backend-test)
      run: pm2 restart backend-test

  deploy-prod: # Deploy to the production environment
    if: github.ref == 'refs/heads/main'
    runs-on: ip-172-31-2-210 # Replace with the label for your prod runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build App
      run: npm run build --if-present

    - name: Restart PM2 (backend-test)
      run: pm2 restart backend-test
